#!/usr/bin/env python3
"""One-time seed script: migrate hardcoded bundles into the SQLite database."""

import json
import os
import sqlite3

DB_PATH = os.path.join(os.path.dirname(__file__), "analytics.db")

BUNDLES = [
    # ── DRINKS ──────────────────────────────────────────────────────────────
    {
        "id": "drinks-4",
        "label": "Any 4 Drinks — $20",
        "type": "quantity",
        "group": "drinks",
        "display_category": "Edibles",
        "quantity": 4,
        "bundle_price": 20,
        "match_criteria": {"subcategoryEquals": "DRINKS"},
    },
    {
        "id": "drinks-6",
        "label": "Any 6 Drinks — $27",
        "type": "quantity",
        "group": "drinks",
        "display_category": "Edibles",
        "quantity": 6,
        "bundle_price": 27,
        "match_criteria": {"subcategoryEquals": "DRINKS"},
    },
    {
        "id": "drinks-8",
        "label": "Any 8 Drinks — $35",
        "type": "quantity",
        "group": "drinks",
        "display_category": "Edibles",
        "quantity": 8,
        "bundle_price": 35,
        "match_criteria": {"subcategoryEquals": "DRINKS"},
    },
    {
        "id": "drinks-case",
        "label": "Build a Drink Case: 24 for $100",
        "type": "quantity",
        "group": "drinks",
        "display_category": "Edibles",
        "quantity": 24,
        "bundle_price": 100,
        "match_criteria": {"subcategoryEquals": "DRINKS", "nameExcludes": ["keef"]},
    },
    # ── PRE-ROLLS ────────────────────────────────────────────────────────────
    {
        "id": "juicy-fire-4pack",
        "label": "Juicy Stickz or Fire Styxx 4-Pack — $42",
        "type": "quantity",
        "group": "juicy-fire",
        "display_category": "Pre-Rolls",
        "quantity": 4,
        "bundle_price": 42,
        "match_criteria": {"nameContains": ["juicy stickz", "fire styxx"]},
    },
    {
        "id": "juicy-fire-6pack",
        "label": "Juicy Stickz or Fire Styxx 6-Pack — $60",
        "type": "quantity",
        "group": "juicy-fire",
        "display_category": "Pre-Rolls",
        "quantity": 6,
        "bundle_price": 60,
        "match_criteria": {"nameContains": ["juicy stickz", "fire styxx"]},
    },
    {
        "id": "hh-1g-preroll-2",
        "label": "Any 2 High Hopes 1G Pre-Rolls — $15",
        "type": "quantity",
        "group": "hh-1g-preroll",
        "display_category": "Pre-Rolls",
        "quantity": 2,
        "bundle_price": 15,
        "match_criteria": {"nameContains": ["high hopes"], "unitWeightContains": ["1g"], "subcategoryNotEquals": "PACKS"},
    },
    {
        "id": "hh-1g-preroll-5",
        "label": "Any 5 High Hopes 1G Pre-Rolls — $35",
        "type": "quantity",
        "group": "hh-1g-preroll",
        "display_category": "Pre-Rolls",
        "quantity": 5,
        "bundle_price": 35,
        "match_criteria": {"nameContains": ["high hopes"], "unitWeightContains": ["1g"], "subcategoryNotEquals": "PACKS"},
    },
    {
        "id": "hh-1g-preroll-10",
        "label": "Any 10 High Hopes 1G Pre-Rolls — $65",
        "type": "quantity",
        "group": "hh-1g-preroll",
        "display_category": "Pre-Rolls",
        "quantity": 10,
        "bundle_price": 65,
        "match_criteria": {"nameContains": ["high hopes"], "unitWeightContains": ["1g"], "subcategoryNotEquals": "PACKS"},
    },
    {
        "id": "hh-5pack-2",
        "label": "Any 2 High Hopes 5-Packs — $45",
        "type": "quantity",
        "display_category": "Pre-Rolls",
        "quantity": 2,
        "bundle_price": 45,
        "match_criteria": {"nameContains": ["high hopes"], "subcategoryEquals": "PACKS"},
    },
    {
        "id": "valorem-1g-2",
        "label": "Any 2 Valorem 1G Pre-Rolls — $15",
        "type": "quantity",
        "display_category": "Pre-Rolls",
        "quantity": 2,
        "bundle_price": 15,
        "match_criteria": {"nameContains": ["valorem"], "unitWeightContains": ["1g"]},
    },
    {
        "id": "realm-1g-2",
        "label": "Any 2 Realm 1G Pre-Rolls — $15",
        "type": "quantity",
        "display_category": "Pre-Rolls",
        "quantity": 2,
        "bundle_price": 15,
        "match_criteria": {"nameContains": ["realm"], "unitWeightContains": ["1g"], "nameExcludes": ["infused", "blunt"]},
    },
    # ── FLOWER ───────────────────────────────────────────────────────────────
    {
        "id": "hh-eighth-3pack",
        "label": "High Hopes Oranguava, Love Truffles & OGKB — 3 for $55",
        "type": "quantity",
        "display_category": "Flower",
        "quantity": 3,
        "bundle_price": 55,
        "match_criteria": {"nameContains": ["oranguava", "love truffles", "ogkb"], "unitWeightContains": ["3.5g", "1/8 oz", "1/8oz"]},
    },
    {
        "id": "friday-flower-2pack",
        "label": "High Hopes Flower 3.5G 2-Pack — $28 (Fridays)",
        "type": "quantity",
        "display_category": "Flower",
        "quantity": 2,
        "bundle_price": 28,
        "schedule_days": [5],
        "match_criteria": {"nameContains": ["high hopes"], "unitWeightContains": ["3.5g", "1/8 oz", "1/8oz"]},
    },
    # ── VAPES ────────────────────────────────────────────────────────────────
    {
        "id": "hellavated-1g-2",
        "label": "Hellavated 1G Carts — 2 for $45",
        "type": "quantity",
        "display_category": "Vapes",
        "quantity": 2,
        "bundle_price": 45,
        "match_criteria": {"nameContains": ["hellavated"], "unitWeightContains": ["1g"], "nameExcludes": ["cloud bar"]},
    },
    {
        "id": "freshly-baked-1g-2",
        "label": "Freshly Baked 1G Carts — 2 for $40",
        "type": "quantity",
        "display_category": "Vapes",
        "quantity": 2,
        "bundle_price": 40,
        "match_criteria": {"nameContains": ["freshly baked"], "unitWeightContains": ["1g"]},
    },
    {
        "id": "fernway-1g-2",
        "label": "Fernway 1G Carts — 2 for $60",
        "type": "quantity",
        "group": "fernway-1g",
        "display_category": "Vapes",
        "quantity": 2,
        "bundle_price": 60,
        "match_criteria": {"nameContains": ["fernway"], "unitWeightContains": ["1g"], "nameExcludes": ["disposable"]},
    },
    {
        "id": "friday-fernway-1g-3",
        "label": "Fernway 1G Carts — 3 for $85 (Fridays)",
        "type": "quantity",
        "group": "fernway-1g",
        "display_category": "Vapes",
        "quantity": 3,
        "bundle_price": 85,
        "schedule_days": [5],
        "match_criteria": {"nameContains": ["fernway"], "unitWeightContains": ["1g"], "nameExcludes": ["disposable"]},
    },
    {
        "id": "select-briq-2g-2",
        "label": "Select Briq 2G Disposables — 2 for $100",
        "type": "quantity",
        "display_category": "Vapes",
        "quantity": 2,
        "bundle_price": 100,
        "match_criteria": {"nameContains": ["select briq"], "unitWeightContains": ["2g"]},
    },
    {
        "id": "crude-strane-4",
        "label": "Crude Boys or Strane Carts — 4 for $100",
        "type": "quantity",
        "display_category": "Vapes",
        "quantity": 4,
        "bundle_price": 100,
        "match_criteria": {"nameContains": ["crude boys", "strane"], "subcategoryEquals": "CARTRIDGES"},
    },
    {
        "id": "dcc-1g-4",
        "label": "DCC 1G Live Resin Carts — 4 for $100",
        "type": "quantity",
        "display_category": "Vapes",
        "quantity": 4,
        "bundle_price": 100,
        "match_criteria": {"nameContains": ["dcc"], "unitWeightContains": ["1g"]},
    },
    # hellavated-strane-cloud-2: split into two bundles in the same group
    {
        "id": "hellavated-cloud-bar-2",
        "label": "Hellavated or Strane 1G Cloud Bars — 2 for $55",
        "type": "quantity",
        "group": "cloud-bar-disposable",
        "display_category": "Vapes",
        "quantity": 2,
        "bundle_price": 55,
        "match_criteria": {"nameContainsAll": ["hellavated", "cloud bar"], "unitWeightContains": ["1g"]},
    },
    {
        "id": "strane-disposable-2",
        "label": "Hellavated or Strane 1G Cloud Bars — 2 for $55",
        "type": "quantity",
        "group": "cloud-bar-disposable",
        "display_category": "Vapes",
        "quantity": 2,
        "bundle_price": 55,
        "match_criteria": {"nameContains": ["strane"], "subcategoryEquals": "DISPOSABLES", "unitWeightContains": ["1g"]},
    },
    # ── DIME DAY ─────────────────────────────────────────────────────────────
    {
        "id": "dime-1g-2",
        "label": "Dime 1G Disposables — 2 for $70 (Dime Day)",
        "type": "quantity",
        "group": "dime-day",
        "display_category": "Vapes",
        "quantity": 2,
        "bundle_price": 70,
        "schedule_dates": [10],
        "match_criteria": {"nameContains": ["dime"], "unitWeightContains": ["1g"]},
    },
    {
        "id": "dime-2g-2",
        "label": "Dime 2G Disposables — 2 for $80 (Dime Day)",
        "type": "quantity",
        "group": "dime-day",
        "display_category": "Vapes",
        "quantity": 2,
        "bundle_price": 80,
        "schedule_dates": [10],
        "match_criteria": {"nameContains": ["dime"], "unitWeightContains": ["2g"]},
    },
    {
        "id": "dime-mix-2",
        "label": "Mix & Match Dime Disposables — 2 for $80 (Dime Day)",
        "type": "quantity",
        "group": "dime-day",
        "display_category": "Vapes",
        "quantity": 2,
        "bundle_price": 80,
        "schedule_dates": [10],
        "match_criteria": {"nameContains": ["dime"], "unitWeightContains": ["1g", "2g"]},
    },
    # ── WAX WEDNESDAYS ───────────────────────────────────────────────────────
    {
        "id": "mac-sugar-2",
        "label": "MAC Sugar — 2 for $55 (Wax Wednesdays)",
        "type": "quantity",
        "group": "mac-sugar",
        "display_category": "Dabs",
        "quantity": 2,
        "bundle_price": 55,
        "schedule_days": [3],
        "match_criteria": {"nameContainsAll": ["mac", "sugar"]},
    },
    {
        "id": "mac-sugar-3",
        "label": "MAC Sugar — 3 for $80 (Wax Wednesdays)",
        "type": "quantity",
        "group": "mac-sugar",
        "display_category": "Dabs",
        "quantity": 3,
        "bundle_price": 80,
        "schedule_days": [3],
        "match_criteria": {"nameContainsAll": ["mac", "sugar"]},
    },
    {
        "id": "mac-live-hash-2",
        "label": "MAC 1G Live Hash Rosin — 2 for $90 (Wax Wednesdays)",
        "type": "quantity",
        "display_category": "Dabs",
        "quantity": 2,
        "bundle_price": 90,
        "schedule_days": [3],
        "match_criteria": {"nameContainsAll": ["mac", "live hash rosin"]},
    },
    # ── EDIBLES ──────────────────────────────────────────────────────────────
    {
        "id": "bettys-fruit-2",
        "label": "Betty's Eddies Fruit Chew 10pk — 2 for $35",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 2,
        "bundle_price": 35,
        "match_criteria": {"nameContains": ["betty's eddies", "bettys eddies"], "nameExcludes": ["caramelt"]},
    },
    {
        "id": "wyld-2",
        "label": "Any 2 Wyld Gummies — $35 (Wednesdays)",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 2,
        "bundle_price": 35,
        "schedule_days": [3],
        "match_criteria": {"nameContains": ["wyld"]},
    },
    {
        "id": "mindys-2",
        "label": "Mindy's — 2 for $35",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 2,
        "bundle_price": 35,
        "match_criteria": {"nameContains": ["mindy's", "mindys"]},
    },
    # ── MONDAY MUNCHDAYS ─────────────────────────────────────────────────────
    {
        "id": "monday-dorks-2",
        "label": "Dorks — 2 for $16 (Monday Munchdays)",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 2,
        "bundle_price": 16,
        "schedule_days": [1],
        "match_criteria": {"nameContains": ["dorks"]},
    },
    {
        "id": "monday-pax-2",
        "label": "Pax Live Rosin — 2 for $40 (Monday Munchdays)",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 2,
        "bundle_price": 40,
        "schedule_days": [1],
        "match_criteria": {"nameContains": ["pax"]},
    },
    {
        "id": "monday-choice-3",
        "label": "Choice Chews — 3 for $24 (Monday Munchdays)",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 3,
        "bundle_price": 24,
        "schedule_days": [1],
        "match_criteria": {"nameContains": ["choice chews"]},
    },
    {
        "id": "monday-camino-2",
        "label": "Camino — 2 for $40 (Monday Munchdays)",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 2,
        "bundle_price": 40,
        "schedule_days": [1],
        "match_criteria": {"nameContains": ["camino"]},
    },
    {
        "id": "monday-bettys-3",
        "label": "Betty's Eddies Fruit Chews — 3 for $52 (Monday Munchdays)",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 3,
        "bundle_price": 52,
        "schedule_days": [1],
        "match_criteria": {"nameContains": ["betty's eddies", "bettys eddies"], "nameExcludes": ["caramelt"]},
    },
    {
        "id": "monday-cannatini-2",
        "label": "Cannatini — 2 for $35 (Monday Munchdays)",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 2,
        "bundle_price": 35,
        "schedule_days": [1],
        "match_criteria": {"nameContains": ["cannatini"]},
    },
    {
        "id": "monday-zzzonked-2",
        "label": "Zzzonked — 2 for $40 (Monday Munchdays)",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 2,
        "bundle_price": 40,
        "schedule_days": [1],
        "match_criteria": {"nameContains": ["zzzonked"]},
    },
    {
        "id": "monday-jams-2",
        "label": "Jams — 2 for $35 (Monday Munchdays)",
        "type": "quantity",
        "display_category": "Edibles",
        "quantity": 2,
        "bundle_price": 35,
        "schedule_days": [1],
        "match_criteria": {"nameContains": ["jams"]},
    },
]


def seed():
    with sqlite3.connect(DB_PATH) as con:
        con.execute(
            """CREATE TABLE IF NOT EXISTS bundles (
              id TEXT PRIMARY KEY,
              label TEXT NOT NULL,
              type TEXT NOT NULL DEFAULT 'quantity',
              grp TEXT,
              display_category TEXT,
              quantity INTEGER,
              bundle_price REAL,
              unit_price REAL,
              schedule_days TEXT,
              schedule_dates TEXT,
              match_criteria TEXT NOT NULL DEFAULT '{}',
              sort_order INTEGER DEFAULT 0,
              enabled INTEGER DEFAULT 1,
              created_at TEXT DEFAULT (datetime('now')),
              updated_at TEXT DEFAULT (datetime('now'))
            )"""
        )
        for b in BUNDLES:
            con.execute(
                """INSERT OR REPLACE INTO bundles
                   (id, label, type, grp, display_category, quantity, bundle_price,
                    unit_price, schedule_days, schedule_dates, match_criteria, sort_order, enabled)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    b["id"],
                    b["label"],
                    b.get("type", "quantity"),
                    b.get("group"),
                    b.get("display_category"),
                    b.get("quantity"),
                    b.get("bundle_price"),
                    b.get("unit_price"),
                    json.dumps(b["schedule_days"]) if b.get("schedule_days") else None,
                    json.dumps(b["schedule_dates"]) if b.get("schedule_dates") else None,
                    json.dumps(b.get("match_criteria", {})),
                    b.get("sort_order", 0),
                    1,
                ),
            )
        con.commit()
    print(f"Seeded {len(BUNDLES)} bundles into {DB_PATH}")


if __name__ == "__main__":
    seed()
